# Background opacity
background_opacity: 0.8

font:
   normal:
      family:
         "MesloLGS NF"
#   normal:
#      family: " GoMono Nerd Font" 
#   bold:
#      family: "Noto Color Emoji" 
#   italic:
#      family: "Noto Color Emoji" 
   size: 8
